#!/bin/bash

# Script to clear (destroy) ZFS snapshots
# Written by Arthur Turrini <turrini@gmail.com>

echo -e "# Will remove these snapshots:"

if [[ -z "$1" ]]; then
    SNAPS=$(env LC_ALL=C sudo zfs list -H -t snapshot -o name -s creation | grep @)
else
    SNAPS=$(env LC_ALL=C sudo zfs list -H -t snapshot -o name -s creation | grep @ | egrep "$1")
fi

printf "%s\n"  "${SNAPS[@]}"
echo -e -n "# Confirm? [y/N]: "
read question

if [[ "$question" != "y" ]]; then
    exit
fi

for SNAP in ${SNAPS[@]}
do
    echo -e "# Destroying $SNAP ..."
    env LC_ALL=C sudo zfs destroy "$SNAP"
done
